### PR TITLE
Load some winapi functions at runtime

### PR DESCRIPTION
**Pull request by seventh-chord**
Certain functions in winapi are only supported on newer versions of windows. If we want to run on older versions, we have to load these functions at runtime. If loading fails, that means that the function is not available. In that case, we have to fall back to doing something else at runtime.

I am running windows 8.1, so I am unable to run the program without these changes. This also means that somebody who runs windows 10 should to test this, to confirm that it still works as expected.

The interesting part of this PR is in `src/util.rs`. Here `fn load_optional_functions` tries to load functions using `kernel32::LoadLibraryA` and `kernel32::GetProcAddress`. The functions are stored in the `OptionalFunctions` struct, which is passed to wherever these functions are needed. If it is desirable, we might be able to store these functions statically somewhere, so we don't have to pass the struct around (I think the `gl` crate does this).

The functions which are currently loaded are:
- `GetDpiForSystem` (https://msdn.microsoft.com/en-us/library/windows/desktop/mt748623(v=vs.85).aspx), windows 10 or later
- `GetDpiForMonitor` (https://msdn.microsoft.com/en-us/library/windows/desktop/dn280510(v=vs.85).aspx), windows 8.1 or later
- `SetProcessDpiAwareness` (https://msdn.microsoft.com/en-us/library/windows/desktop/dn302122(v=vs.85).aspx), windows 10 or later

### CODE REVIEW

**Comment by raphlinus** [comment]
Unfortunately, this is not working properly on Windows 10. It builds and runs correctly, but then it prints:

```
Could not load `GetDpiForSystem`. Windows 10 or later is needed
Could not load `SetProcessDpiAwareness`. Windows 10 or later is needed
```

And then it doesn't display in hi-dpi at all.

I could try to debug this, but maybe that's enough of a clue to figure out what's going wrong?

Thanks for the effort, I appreciate it.

**Comment by raphlinus** [comment]
Ack, accidentally merged, sorry about that.

**Comment by seventh-chord** [comment]
Ok, I think the issue is just that I made a silly mistake. `GetDpiForSystem` comes from `user32`, while `SetProcessDpiAwareness` comes from `shcore`, but I had it the other way around in code. Also, `SetProcessDpiAwareness` is available on windows 8.1, so I can test that.

I'll have a commit ready in a few minutes, just need to test stuff.

Should I open another PR since this one is closed? Not quite sure how to do this without messing up git :/

**Comment by raphlinus** [comment]
Yes, this works fine and I'm happy to merge it. There's probably some fancy way to update a merged PR, but it's probably just easiest to open a new one. Thanks for seeing this through.

**Pull request merged**
